version: "3.9"

services:
  backend:
    container_name: lab_inventory_backend_test
    image: lab-inventory-main-backend-test
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    networks:
      - lab_inventory_net_test

  frontend:
    container_name: lab_inventory_frontend_test
    image: lab-inventory-main-frontend-test
    build:
      context: ./lab-inventory-ui
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    networks:
      - lab_inventory_net_test
    volumes:
      - ./lab-inventory-ui:/app

  db:
    container_name: lab_inventory_db_test
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab_inventory_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    networks:
      - lab_inventory_net_test

volumes:
  backend_data_test:
  postgres_data_test:

networks:
  lab_inventory_net_test:
