version: "3.9"

services:
  backend:
    container_name: lab_inventory_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - lab_inventory_net
    volumes:
      - backend_data:/app

  frontend:
    container_name: lab_inventory_frontend
    build:
      context: ./lab-inventory-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - lab_inventory_net
    volumes:
      - ./lab-inventory-ui:/app

  db:
    container_name: lab_inventory_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab_inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lab_inventory_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  backend_data:
  postgres_data:

networks:
  lab_inventory_net:
